# Configuration du scraper d'emploi
user_profile:
  # Compétences principales (séparées par des virgules)
  skills: "Python, JavaScript, React, Node.js, TypeScript, SQL, PostgreSQL, MongoDB, Docker, Kubernetes, AWS, GCP, Git, CI/CD, Django, Flask, FastAPI, Vue.js, HTML, CSS, Linux, DevOps, Machine Learning, Data Science"
  
  # Expérience en années
  experience_years: 5
  
  # Niveau d'éducation
  education_level: "Ingénieur"

# Critères de recherche
search_criteria:
  # Mots-clés pour le poste recherché
  keywords: ["ingénieur logiciel", "développeur full stack", "software engineer", "full stack developer", "développeur web", "tech lead", "senior developer", "python developer", "javascript developer"]
  
  # Localisations multiples (séparées par des virgules)
  locations: [
    "Genève, Suisse",
    "Lausanne, Suisse", 
    "Vaud, Suisse",
    "Fribourg, Suisse",
    "Neuchâtel, Suisse",
    "Jura, Suisse",
    "Valais, Suisse",
    "Lille, France",
    "Métropole Lilloise",
    "Nord, France",
    "Suisse romande",
    "télétravail"
  ]
  
  # Salaire minimum souhaité (en euros annuels)
  salary_min: 60000
  
  # Salaire maximum souhaité (en euros annuels)
  salary_max: 120000
  
  # Type de contrat
  contract_types: ["CDI", "Freelance", "Mission longue"]
  
  # Télétravail accepté
  remote_ok: true

# Sites à scraper
job_sites:
  - name: "Indeed"
    url: "https://fr.indeed.com"
    enabled: true
  
  - name: "LinkedIn"
    url: "https://www.linkedin.com"
    enabled: false  # Nécessite une authentification
  
  - name: "Welcome to the Jungle"
    url: "https://www.welcometothejungle.com"
    enabled: true

# Paramètres du scraper
scraper_settings:
  # Délai entre les requêtes (en secondes)
  delay_between_requests: 2
  
  # Nombre maximum d'offres à récupérer par site
  max_jobs_per_site: 50
  
  # Timeout pour les requêtes (en secondes)
  request_timeout: 30
  
  # User agent pour les requêtes
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  
  # === NOUVEAUX PARAMÈTRES V2 ===
  
  # Paramètres de recherche Google
  max_google_queries: 15          # Nombre maximum de requêtes Google
  max_results_per_query: 30       # Résultats max par requête Google
  delay_between_queries: 8        # Délai entre requêtes Google (secondes)
  
  # Paramètres généraux v2
  max_jobs_total: 150             # Nombre maximum d'offres à traiter
  headless: false                 # Mode sans interface (true = plus rapide, false = plus discret)
  
  # Paramètres anti-détection
  random_delays: true             # Délais aléatoires entre actions
  rotate_user_agents: true        # Rotation des User-Agents
  
  # Paramètres de performance
  parallel_scraping: false        # Scraping parallèle (expérimental)
  batch_size: 10                  # Taille des lots pour le scraping