# Configuration du scraper d'emploi
user_profile:
  # Compétences principales (séparées par des virgules)
  skills: 'Python, JavaScript, React, Node.js, Next.js, TypeScript, SQL, PostgreSQL, MongoDB, Docker, Kubernetes, Git, CI/CD, Django, Flask, FastAPI, Vue.js, HTML, CSS'

  # Expérience en années
  experience_years: 4

  # Niveau d'éducation
  education_level: 'Ingénieur'

# Critères de recherche
search_criteria:
  # Mots-clés pour le poste recherché
  keywords:
    [
      'développeur Next.js',
      'développeur full stack',
      'full stack developer',
      'tech lead',
      'python developer',
      'Ingénieur Full Stack Next.js',
      'Développeur React',
      'Ingénieur Full Stack',
    ]

  # Localisations multiples (séparées par des virgules)
  locations:
    [
      'Genève, Suisse',
      'Lausanne, Suisse',
      'Vaud, Suisse',
      'Fribourg, Suisse',
      'Neuchâtel, Suisse',
      'Jura, Suisse',
      'Valais, Suisse',
      'Lille, France',
      'Métropole Lilloise',
      'Nord, France',
      'Suisse romande',
      'full remote',
    ]

  # Salaire minimum souhaité (en euros annuels)
  salary_min: 40000

  # Salaire maximum souhaité (en euros annuels)
  salary_max: 1000000

  # Type de contrat
  contract_types: ['CDI', 'Freelance', 'Mission longue']

  # Télétravail accepté
  remote_ok: true

# Configuration des APIs et sources de données
api_settings:
  # Sources d'emploi activées (Adzuna, Indeed RSS, RapidAPI)
  enabled_sources:
    - 'adzuna_api' # API Adzuna (nécessite clés API dans .env)
    - 'indeed_rss' # Indeed RSS (gratuit, pas de clé nécessaire)
    - 'rapidapi_jobs' # Jobs via RapidAPI (nécessite clé RapidAPI dans .env)

  # Limites par source pour éviter les quotas
  max_results_per_source: 25

  # Délais entre requêtes API (secondes)
  api_delay: 2

  # Timeout pour les requêtes API (secondes)
  api_timeout: 15

# Paramètres du scraper
scraper_settings:
  # Nombre maximum total d'offres à traiter
  max_jobs_total: 100

  # Score minimum de pertinence à conserver (0-100)
  min_match_score: 30

  # Délai aléatoire entre sources pour éviter la détection
  random_delay_min: 3
  random_delay_max: 6

  # User agent moderne pour les requêtes
  user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

# Critères de scoring avancé
scoring_criteria:
  # Poids des différents critères (total = 100%)
  skills_weight: 40 # Correspondance des compétences
  location_weight: 30 # Proximité géographique
  remote_weight: 15 # Possibilité télétravail
  source_weight: 15 # Fiabilité de la source

  # Bonus pour certains mots-clés
  bonus_keywords:
    - 'senior': 10
    - 'lead': 15
    - 'architect': 20
    - 'remote': 15
    - 'télétravail': 15
